apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-onkyo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onkyo
  template:
    metadata:
      labels:
        app: onkyo
        context: sentinel
        version: v1
    spec:
      containers:
      -
        name: app
        image: docker.io/hashneo/sentinel-svc-onkyo-x86_64:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        - name: CONSUL
          value: "consul"
        - name: NEW_RELIC_NO_CONFIG_FILE
          value: "true"
        - name: NEW_RELIC_ENABLED
          value: "true"
        - name: NEW_RELIC_APP_NAME
          value: "Sentinel Onkyo"
        - name: NEW_RELIC_LICENSE_KEY
          value: ""
        ports:
        -
          containerPort: 5000
          protocol: TCP
        -
          containerPort: 60128
          protocol: UDP
      nodeSelector:
        beta.kubernetes.io/arch: amd64
